spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.9.130:3307/library-management-system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

server:
  port: 80

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:config/mapper/*.xml
  type-aliases-package: cn.gl.librarymanagementsystem.bean

